from __future__ import annotations

import re

from dotenv import load_dotenv

from src.knowledge.locator_registry import build_registry_prompt_context, get_locator_profile
from src.llm.ollama_client import chat_with_ollama
from src.llm.prompts import generator_system_prompt
from src.mcp.snapshot_artifact import require_valid_mcp_snapshot
from src.use_cases.use_case_manager import (
    get_use_case_paths,
    load_use_case_config,
    parse_use_case_args,
)
from src.utils.file_utils import file_exists, read_text_file, resolve_project_path, write_text_file
from src.utils.logger import error, info


def extract_python(response: str) -> str:
    fenced_code_match = re.search(r"```(?:python)?\s*([\s\S]*?)```", response, re.IGNORECASE)
    return fenced_code_match.group(1).strip() if fenced_code_match else response.strip()


def main() -> None:
    load_dotenv()
    args = parse_use_case_args("Generate Python Playwright code for a selected Teamcenter use case.")
    use_case_paths = get_use_case_paths(args.use_case)
    use_case_config = load_use_case_config(args.use_case)
    manual_steps_path = use_case_paths.manual_steps_path
    csv_path = use_case_paths.input_data_path
    test_plan_path = use_case_paths.test_plan_path
    mcp_snapshot_path = use_case_paths.mcp_snapshot_path
    locator_candidates_path = use_case_paths.locator_candidates_path
    locator_knowledge_path = resolve_project_path("src", "knowledge", "teamcenterLocators.md")
    flows_knowledge_path = resolve_project_path("src", "knowledge", "teamcenterFlows.md")
    output_path = use_case_paths.generated_code_path

    manual_steps = read_text_file(manual_steps_path)
    csv_data = read_text_file(csv_path)
    test_plan = read_text_file(test_plan_path)
    if not file_exists(mcp_snapshot_path):
        raise RuntimeError(
            "Playwright MCP snapshot file is missing. Run `python -m src.agents.mcp_snapshot_agent` before code generation."
        )

    registry_context = build_registry_prompt_context()
    mcp_snapshot = require_valid_mcp_snapshot(
        read_text_file(mcp_snapshot_path),
        "Code generation",
    )
    locator_candidates = read_text_file(locator_candidates_path)
    locator_knowledge = read_text_file(locator_knowledge_path)
    flow_knowledge = (
        read_text_file(flows_knowledge_path)
        if file_exists(flows_knowledge_path)
        else "No Teamcenter flow knowledge file was provided."
    )

    framework_rules = "\n".join(
        [
            "- Use Python Playwright.",
            "- Use Page Object Model concepts.",
            "- Keep generated code separate from stable reviewed tests.",
            "- Avoid hard waits.",
            "- Use Playwright expect assertions.",
            "- Capture screenshot evidence for each part.",
            "- Add TODO comments for unknown Teamcenter locators.",
        ]
    )

    info(
        "Generating Python Playwright code with Ollama using the required MCP snapshot "
        "and structured locator registry."
    )
    response = chat_with_ollama(
        [
            {"role": "system", "content": generator_system_prompt},
            {
                "role": "user",
                "content": "\n".join(
                    [
                        (
                            "Generate a Python Playwright automation file for the Teamcenter "
                            f"`{use_case_config['displayName']}` use case."
                        ),
                        "",
                        "## Manual Steps",
                        manual_steps,
                        "",
                        "## CSV Structure",
                        csv_data,
                        "",
                        "## Structured Test Plan",
                        test_plan,
                        "",
                        "## Locator Candidates",
                        locator_candidates,
                        "",
                        "## Locator Knowledge",
                        locator_knowledge,
                        "",
                        f"## Structured Locator Registry Profile\n{get_locator_profile()}",
                        "",
                        registry_context,
                        "",
                        "## Required Playwright MCP Browser Snapshot",
                        mcp_snapshot,
                        "",
                        "## Flow Knowledge",
                        flow_knowledge,
                        "",
                        "## Framework Rules",
                        framework_rules,
                    ]
                ),
            },
        ]
    )

    generated_code = extract_python(response)
    reviewed_header = "\n".join(
        [
            "# Generated by src/agents/generator_agent.py using the hosted Ollama endpoint.",
            "# Review this file before promoting any of its content into stable tests.",
            "",
        ]
    )

    write_text_file(output_path, reviewed_header + generated_code + "\n")
    info(f"Saved generated Playwright code to {output_path}")


if __name__ == "__main__":
    try:
        main()
    except Exception as caught:
        error(f"Generator agent failed: {caught}")
        raise
